### PR TITLE
Bump gen_smtp version to address Rebar 2 deprecation warning

### PR DESCRIPTION
**Pull request by kyleboe**
Elixir 1.13 shows a deprecation warning for Rebar 2 which was a dependency of `hut`, a dependency of `gen_smtp < 1.2.0`.

```
dependency :hut is using Rebar 2, which is no longer maintained and no longer works in recent Erlang/OTP versions. Remove the :manager option or set it to :rebar3 instead
```

Bumping to `gen_smtp ~> 1.2.0` removes the dependency on `hut`

### CODE REVIEW

**Comment by kyleboe** [comment]
Resolves #206

**Comment by kyleboe** [comment]
@tgautier thoughts on how to support something like this?

It seems like there are issues with backwards compatibility. Not sure if it should be handled in a major version (or pre-release thereof) or if I'm just missing something in the CI pipelines.

**Comment by deepankar-j** [comment]
This PR will also address Issue https://github.com/fewlinesco/bamboo_smtp/issues/192.

**Comment by kyleboe** [comment]
@tgautier Bump. Would appreciate your input on [this](https://github.com/fewlinesco/bamboo_smtp/pull/205#issuecomment-1109882905). Thanks!

**Comment by jbcden** [comment]
> @tgautier Bump. Would appreciate your input on [this](https://github.com/fewlinesco/bamboo_smtp/pull/205#issuecomment-1109882905). Thanks!

No idea if this would work but does restricting the version of `ranch` to `2.0.0` do it? I can't get erlang 20.3 to install locally at the moment but it shows up in the error messages so maybe it's worth a try? Sorry if you've already tried that :sweat:

**Comment by kyleboe** [comment]
Ok I was able to get tests to all pass locally on elixir 1.8.2 and OTP 22 by locking the ranch version to 2.0.0 as suggested above (thanks @jbcden!). Apologies for my slow response on this.

**Comment by kyleboe** [comment]
Dang. Looks like there were issues on OTP < 21. Thoughts on dropping support for it? Or maybe adding a deprecation warning of some kind? Or maybe cutting a new major version?

**Comment by kyleboe** [comment]
Or another alternative would be dropping the `--warnings-as-errors` flag from the `mix compile` in the specs? There are some errors that seem fairly isolated to older versions of elixir/otp/deps

**Comment by jbcden** [comment]
> Dang. Looks like there were issues on OTP < 21. Thoughts on dropping support for it? Or maybe adding a deprecation warning of some kind? Or maybe cutting a new major version?

@kyleboe it looks like it might be better to drop. It looks like `gen_smtp` defines its minimum OTP version as 21: https://github.com/gen-smtp/gen_smtp/blob/master/rebar.config#L2.

**Comment by kyleboe** [comment]
Removed OTP < 21 support and bumped to latest versions of OTP in the `bamboo_smtp.yml` matrix.

**Comment by kyleboe** [comment]
I finally stopped being a doofus and just ran GH actions on my fork of the repo and got everything passing! https://github.com/kyleboe/bamboo_smtp/actions/runs/2477937365

**Comment by kyleboe** [comment]
Anyone from the maintainers have a chance to review and trigger CI? @babariviere possibly?

**Comment by babariviere** [comment]
> Anyone from the maintainers have a chance to review and trigger CI? @babariviere possibly?

Hello, I am no longer part of the organization so I won't be able to merge it! Sorry for that.

**Comment by kyleboe** [comment]
Ah Sorry to bother you.

@tgautier looks to be responsible for the most recent PR merge. Could you help with review/merge?

**Comment by adamu** [comment]
Thanks for persisting with this @kyleboe! I tried tweeting them to see if we can get any engagement. https://twitter.com/_adamu_/status/1536947307526369280

Somebody will need to publish to Hex too, it looks like the owners there might be different to this Github repo now? https://hex.pm/packages/bamboo_smtp

**Review by tgautier — APPROVED** [review]

**Comment by adamu** [comment]
Unfortunately the pin to `ranch` 2.0.0 makes this conflict with the latest (2.9.0) version of `cowboy`, which requires 1.8.0. `gen_smtp` specifies `>= 1.8.0` FWIW.

**Pull request merged**
