### PR TITLE
Upgrading bamboo to 1.0.0-rc

### PR DESCRIPTION
**Pull request by kelvinst**
Just making it work with the new version of bamboo to come.

### CODE REVIEW

**Comment by tgautier** [comment]
Thanks for the notification!

We didn't notice that a RC was available for Bamboo although it was released in May 😥 

I don't know yet how we're going to handle this on our side.

I guess we can create a rc once this is merged on `develop`, the logic would be a `1.4.0-rc.1`.

Would this be ok for you?

@kdisneur I'd like your input on this one 😉

**Comment by kdisneur** [comment]
Yes I also missed the Bamboo release :(

@tgautier we already published a 1.4.0 on Hex so, I would suggest a 1.5.0-rc.1

**Comment by tgautier** [comment]
@kdisneur Oh yes sorry, I meant `1.5.0.rc.1` 😉

**Comment by kelvinst** [comment]
Sure it's ok for me!

**Pull request merged**
