### PR TITLE
Update mix.exs gen_smtp dependency 1.0.1 to 1.1.0

### PR DESCRIPTION
**Pull request by LatitudeAdjustment**
- Latest gen_smtp release (1.1.0) uses Ranch >= 1.7.0
- Bump gen_smtp dependency in bamboo_smtp from 1.0.1 to 1.1.0
- Update allows use of bamboo_smtp in Phoenix 1.5+, resolves underlying upgrade Cowboy/Ranch dependency issues like the following:

```
Failed to use "ranch" (version 1.7.1) because
  cowboy (version 2.8.0) requires ~> 1.7.1
  gen_smtp (version 1.0.1) requires 1.6.2
```

- Requires Erlang/OTP 20+

https://ninenines.eu/articles/cowboy-2.7.0/

Excerpts regarding Erlang/OTP compatibility from 99s:

```
This is the first Cowboy version that is compatible with the upcoming Ranch 2.0. 
Cowboy 2.7 will use Ranch 1.7.1 by default.
```
```
Cowboy 2.7 requires Erlang/OTP 20 or above and is tested and supported on Linux, FreeBSD, macOS and Windows
```

- Removed tests for OTP 19.3

### CODE REVIEW

**Comment by babariviere** [comment]
Hello 👋 
Thanks for your PR!

As you have updated `mix.exs`, can you also update the `mix.lock` file?
You can do the following:

```sh
mix deps.update bamboo gen_smtp
```

**Comment by LatitudeAdjustment** [comment]
Yes, thanks, should have checked in mix.lock along with mix.exs.

**Review by babariviere — APPROVED** [review]

**Review by arnaudmorisset — APPROVED** [review]

**Review by MatheusBueno782 — APPROVED** [review]

**Comment by wingyplus** [comment]
Screen Shot 2564-02-10 at 22 50 10

Is ci hang?

**Comment by babariviere** [comment]
@wingyplus yes, I am checking it right now 😄

**Comment by LatitudeAdjustment** [comment]
I don't believe tests for OTP < 20 should be run.
```
Test on Elixir 1.7.4 / OTP 19.3 Expected — Waiting for status to be reported
```

**Pull request merged**
