### PR TITLE
Update Elixir, OTP and all deps to latest versions available

### PR DESCRIPTION
**Pull request by tgautier**
EDIT: Problems are solved, see below for more details.

This PR updates Elixir to `1.4.5` and OTP to `20.0` which are the latest versions available.

I've also updated the matrix of versions on Travis CI to reflect on those changes.

## History

This is not the usual `mix deps.update --all` routine as we have two problems to discuss

1. The update of credo to the latest versions added a new rule regarding pattern matching consistency. You can see here for details ([#197]). As I don't like the new default, I've added a new rule to our configuration to ignore this new check.

2. The package `earmark` is no longer compatible with Elixir prior to `1.4`, should we also remove the support of Elixir pre `1.4` in our tests or should we set the `earmark` version? (this is why the tests are failing on Travis 😢)

[#197]: https://github.com/rrrene/credo/pull/197

### CODE REVIEW

**Comment by kdisneur** [comment]
I would drop the support for Elixir pre 1.4. If some people report they still use it. We will still be able to:

1. backport patches on BambooSMTP 1.4.X
2. suggest to upgrade Elixir 😇 

What do you think?

**Comment by kdisneur** [comment]
My only concern is Bamboo. They still support Elixir 1.2

**Comment by tgautier** [comment]
> 1. backport patches on BambooSMTP 1.4.X
> 2. suggest to upgrade Elixir

Agreed

> My only concern is Bamboo. They still support Elixir 1.2

I also share your apprehension on this point but it seems that they're not running their test suite on multiple versions of Elixir even if their `mix.exs` is `elixir: "~> 1.2"` 😞

**Comment by tgautier** [comment]
I've updated the description and fixed the different issues remaining. I'm awaiting your reviews.

**Review by Fenntasy — APPROVED** [review]

**Pull request merged**
