### PR TITLE
add auth option

### PR DESCRIPTION
**Pull request by paulzql**
add auth option

### CODE REVIEW

**Comment by kdisneur** [comment]
Hello @paulzql 

Thanks (again) for the Pull-Request. 😇 

The tests are failing because Credo (the linter) force the line length to be less or equal to 120 but it looks like you added a line with 121 characters:

```
┃ [R] ↓ Line is too long (max is 120, was 121).
┃       lib/bamboo/adapters/smtp_adapter.ex:40:121 #(Bamboo.SMTPAdapter)
```

Linked to #87

**Comment by jerrett** [comment]
I actually need this as well, for usage with AWS SES

**Comment by kdisneur** [comment]
Hi @paulzql, 

Is it ok if I fix the linter issue myself in order to be able to merge your pull-request?

Thanks :)

**Comment by kdisneur** [comment]
Thanks @paulzql for your PR. We merged #89 which contain your fix.

@jerrett: We will do a new release containing the auth options really soon.

**Comment by kdisneur** [comment]
@jerrett We just released v1.5.0-rc.4

**Pull request closed without merging**
